const legendImages = [
	{
		src: "../images/ash-full.png",
		alt: "Ash Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Ash_square.png",
		altMobile: "Ash Mobile",
	},
	{
		src: "../images/ballistic-full.png",
		alt: "Ballistic Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Ballistic_square.png",
		altMobile: "Ballistic Mobile",
	},
	{
		src: "../images/bangalore-full.png",
		alt: "Bangalore Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Bangalore_square.png",
		altMobile: "Bangalore Mobile",
	},
	{
		src: "../images/bloodhound-full.png",
		alt: "Bloodhound Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Bloodhound_square.png",
		altMobile: "Bloodhound Mobile",
	},
	{
		src: "../images/catalyst-full.png",
		alt: "Catalyst Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Catalyst_square.png",
		altMobile: "Catalyst Mobile",
	},
	{
		src: "../images/caustic-full.png",
		alt: "Caustic Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Caustic_square.png",
		altMobile: "Caustic Mobile",
	},
	{
		src: "../images/crypto-full.png",
		alt: "Crypto Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Crypto_square.png",
		altMobile: "Crypto Mobile",
	},
	{
		src: "../images/fuse-full.png",
		alt: "Fuse Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Fuse_square.png",
		altMobile: "Fuse Mobile",
	},
	{
		src: "../images/gibby-full.png",
		alt: "Gibby Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Gibraltar_square.png",
		altMobile: "Gibby Mobile",
	},
	{
		src: "../images/horizon-full.png",
		alt: "Horizon Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Horizon_square.png",
		altMobile: "Horizon Mobile",
	},
	{
		src: "../images/lifeline-full.png",
		alt: "Lifeline Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Lifeline_square.png",
		altMobile: "Lifeline Mobile",
	},
	{
		src: "../images/loba-full.png",
		alt: "Loba Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Loba_square.png",
		altMobile: "Loba Mobile",
	},
	{
		src: "../images/maggie-full.png",
		alt: "Maggie Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Mad_Maggie_square.png",
		altMobile: "Maggie Mobile",
	},
	{
		src: "../images/mirage-full.png",
		alt: "Mirage Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Mirage_square.png",
		altMobile: "Mirage Mobile",
	},
	{
		src: "../images/newcastle-full.png",
		alt: "Newcastle Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Newcastle_square.png",
		altMobile: "Newcastle Mobile",
	},
	{
		src: "../images/octane-full.png",
		alt: "Octane Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Octane_square.png",
		altMobile: "Octane Mobile",
	},
	{
		src: "../images/pathfinder-full.png",
		alt: "Pathfinder Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Pathfinder_square.png",
		altMobile: "Pathfinder Mobile",
	},
	{
		src: "../images/rampart-full.png",
		alt: "Rampart Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Rampart_square.png",
		altMobile: "Rampart Mobile",
	},
	{
		src: "../images/rev-full.png",
		alt: "Revenant Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Revenant_square.png",
		altMobile: "Revenant Mobile",
	},
	{
		src: "../images/seer-full.png",
		alt: "Seer Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Seer_square.png",
		altMobile: "Seer Mobile",
	},
	{
		src: "../images/valk-full.png",
		alt: "Valk Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Valkyrie_square.png",
		altMobile: "Valk Mobile",
	},
	{
		src: "../images/vantage-full.png",
		alt: "Vantage Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Vantage_square.png",
		altMobile: "Vantage Mobile",
	},
	{
		src: "../images/wattson-full.png",
		alt: "Wattson Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Wattson_square.png",
		altMobile: "Wattson Mobile",
	},
	{
		src: "../images/wraith-full.png",
		alt: "Wraith Desktop",
		mobileSrc: "../images/legends-mobile/Portrait_Wraith_square.png",
		altMobile: "Wraith Mobile",
	},
];

export default legendImages;
